spring.application.name=bottelx

server.port=8080
# spring.datasource.url=jdbc:postgresql://localhost:5432/bottlexdb
# spring.datasource.username=postgres
# spring.datasource.password=1234

spring.datasource.url=jdbc:postgresql://ep-jolly-snow-aq34z0us-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_ctbDJ9UBg1CF
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true



 